import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const inter = localFont({
  src: "./fonts/inter-font.ttf",
  display: "swap",
});

const ibm_plex = localFont({
  src: "./fonts/IBMPlexMono-Regular.ttf",
  display: "swap",
  variable: "--font-ibm-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${ibm_plex.variable} bg-gray-950 text-white antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
